version: '3.1'

services:
  db: 
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: local_development
    volumes:
      - 'mariadb:/var/lib/mysql'
  redis: 
    image: 'redis:alpine'
    ports:
      - 6379:6379
    restart: always
  minio:
    image: 'minio/minio:latest'
    ports:
      - 9000:9000
      - 8900:8900
    volumes:
      - 'minio:/data/minio'
    restart: always
    environment:
      MINIO_ROOT_USER: adminuser
      MINIO_ROOT_PASSWORD: adminuser
    command: minio server /data/minio --console-address ":8900"
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports: 
      - 1025:1025
      - 8025:8025
volumes:
  minio:
    driver: local
  mariadb:
    driver: local